In [2]:
import torch
import einops as e

In [41]:
A = torch.tensor([
    [1, 3, 1],
    [2, 2, 2],
    [5, 5, 5],
])

B = torch.tensor([
    [0, 1, 7],
    [1, 1, 0],
    [1, 1, 1],
])

In [57]:
e.einsum(A, B, 'i j, k j -> i k')

tensor([[10,  4,  5],
        [16,  4,  6],
        [40, 10, 15]])

In [79]:
A = torch.arange(10)
B = torch.arange(5, 15)
print(f'A: {A}')
print(f'B: {B}')
print('-' * 40)

print(e.einsum(A, 'i ->'))
print(e.reduce(A, 'i ->', 'sum'))
print('-' * 40)

print(e.einsum(A, B, 'i, i -> i'))
print('-' * 40)

print(e.einsum(A, B, 'i, i -> '))
print('-' * 40)

print(e.einsum(A, B, 'i, j -> i j'))
print('-' * 40)

C = torch.arange(25).reshape((5, 5))
print(f'C: {C}')
print(e.einsum(C, 'i i -> '))

A: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
B: tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
----------------------------------------
tensor(45)
tensor(45)
----------------------------------------
tensor([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])
----------------------------------------
tensor(510)
----------------------------------------
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
        [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
        [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
        [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
        [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
        [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
        [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
        [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
        [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])
----------------------------------------
C: tens

In [82]:
D = e.repeat(torch.arange(-2, 3), 'i -> 5 i')
print(f'D: {D}')
e.einsum(C, D, 'i j, j i -> i j')

D: tensor([[-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2]])


tensor([[ 0, -2, -4, -6, -8],
        [-5, -6, -7, -8, -9],
        [ 0,  0,  0,  0,  0],
        [15, 16, 17, 18, 19],
        [40, 42, 44, 46, 48]])

In [83]:
e.einsum(C, D, 'i j, k l -> i j k l')

tensor([[[[  0,   0,   0,   0,   0],
          [  0,   0,   0,   0,   0],
          [  0,   0,   0,   0,   0],
          [  0,   0,   0,   0,   0],
          [  0,   0,   0,   0,   0]],

         [[ -2,  -1,   0,   1,   2],
          [ -2,  -1,   0,   1,   2],
          [ -2,  -1,   0,   1,   2],
          [ -2,  -1,   0,   1,   2],
          [ -2,  -1,   0,   1,   2]],

         [[ -4,  -2,   0,   2,   4],
          [ -4,  -2,   0,   2,   4],
          [ -4,  -2,   0,   2,   4],
          [ -4,  -2,   0,   2,   4],
          [ -4,  -2,   0,   2,   4]],

         [[ -6,  -3,   0,   3,   6],
          [ -6,  -3,   0,   3,   6],
          [ -6,  -3,   0,   3,   6],
          [ -6,  -3,   0,   3,   6],
          [ -6,  -3,   0,   3,   6]],

         [[ -8,  -4,   0,   4,   8],
          [ -8,  -4,   0,   4,   8],
          [ -8,  -4,   0,   4,   8],
          [ -8,  -4,   0,   4,   8],
          [ -8,  -4,   0,   4,   8]]],


        [[[-10,  -5,   0,   5,  10],
          [-10,  -5,   0, 